```{r}

```

```{r}
install.packages(c("readxl", "dplyr", "ggplot2", "tidyr"))
```

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
# Загрузка датасета pima
pima <- read_excel("pima.xlsx")

```

```{r}

```

```{# Просмотр первых строк}
head(pima)

```

```{r}
summary_stats <- pima %>%
  select(glucose, pressure, mass) %>%
  summarise_all(list(
    count = ~sum(!is.na(.)),
    mean = ~mean(., na.rm = TRUE),
    sd = ~sd(., na.rm = TRUE),
    Q1 = ~quantile(., 0.25, na.rm = TRUE),
    Q3 = ~quantile(., 0.75, na.rm = TRUE),
    min = ~min(., na.rm = TRUE),
    max = ~max(., na.rm = TRUE)
  ))

summary_stats %>% pivot_longer(everything())

```

```{r}
# Описательная статистика для diabetes
table(pima$diabetes)

# Создание новой переменной age_group
pima <- pima %>%
  mutate(age_group = case_when(
    age >= 21 & age <= 35 ~ "21–35",
    age >= 36 & age <= 49 ~ "36–49",
    age >= 50 ~ "50+",
    TRUE ~ NA_character_
  ))

# Частота по группам
age_group_stats <- table(pima$age_group)
age_group_stats

```

```{r}
ggplot(pima, aes(x = diabetes, y = glucose, fill = diabetes)) +
  geom_boxplot() +
  labs(title = "Ящики с усами для glucose по значениям diabetes",
       x = "Diabetes", y = "Glucose") +
  theme_minimal()

```

```{r}
set.seed(123)

sample_size <- 30

# Допустим, среднее давление до лечения = 150, после = 140, sd = 10
before <- rnorm(sample_size, mean = 150, sd = 10)
after <- rnorm(sample_size, mean = 140, sd = 10)

# Проведем парный t-тест
t_test_result <- t.test(before, after, paired = TRUE)

# Вывод результатов
t_test_result

```
